### ISSUE TITLE
registration / login

### ISSUE THREAD

**Issue by FelixSellmair** [davidetaibi/unibz-serendipity#24]
possibility for user to
- register for serendipity or
- login with facebook or
- login with google

**Comment by davidetaibi** [comment]
https://www.mobile-grid.com/workbench/drupal-servicesrest-and-mobile-devices-using-android-example

https://www.drupal.org/node/910598

**Comment by davidetaibi** [comment]
waiting for MT inputs

**Comment by davidetaibi** [comment]
Example on how to login with android 
https://github.com/ajinkyakulkarni/DrupalAndroidApp
video https://www.youtube.com/watch?v=ezk_21sfEQM

**Comment by FallenRiteMonk** [comment]
2h
